name: "Setup Tests Dependencies"
description: "Installs the dependencies for the tests"

runs:
  using: "composite"
  steps:
    - name: Install Python and UV
      uses: astral-sh/setup-uv@v5.4.0
      with:
        pyproject-file: "tests/pyproject.toml"
        enable-cache: true
    - name: Set up Just
      uses: extractions/setup-just@v2
    - name: Install Python Dependencies
      shell: bash
      run: just tests::install
