version: 2

updates:
  - package-ecosystem: "github-actions"
    directories:
      - "/"
      - ".github/actions/setup-scanner-dependencies"
      - ".github/actions/setup-diagrams-dependencies"
      - ".github/actions/setup-tests-dependencies"
    schedule:
      interval: "cron"
      cronjob: "30 7,12,17 * * *"
    target-branch: "main"
    groups:
      github-actions:
        patterns:
          - "*"
        update-types:
          - "patch"
          - "minor"

  - package-ecosystem: "uv"
    directories:
      - "/scanner"
      - "/diagrams"
      - "/tests"
    schedule:
      interval: "cron"
      cronjob: "30 7,12,17 * * *"
    target-branch: "main"
    groups:
      python:
        patterns:
          - "*"
        update-types:
          - "patch"
          - "minor"

  - package-ecosystem: "npm"
    directory: "dashboard"
    schedule:
      interval: "cron"
      cronjob: "30 7,12,17 * * *"
    target-branch: "main"
    groups:
      typescript:
        patterns:
          - "*"
        update-types:
          - "patch"
          - "minor"
