version: 2

updates:
  - package-ecosystem: "github-actions"
    directories:
      - "/"
      - ".github/actions/setup-scanner-dependencies"
      - ".github/actions/setup-tests-dependencies"
      - ".github/actions/setup-dashboard-dependencies"
    schedule:
      interval: "cron"
      cronjob: "30 7 * * *"
      timezone: "Europe/London"
    target-branch: "main"
    groups:
      github-actions:
        applies-to: "version-updates"
        patterns:
          - "*"
        exclude-patterns:
          - "super-linter/super-linter"
          - "JackPlowman/reusable-workflows"
        update-types:
          - "patch"
          - "minor"

  - package-ecosystem: "uv"
    directories:
      - "/scanner"
      - "/tests"
    schedule:
      interval: "cron"
      cronjob: "30 7 * * *"
      timezone: "Europe/London"
    target-branch: "main"
    groups:
      python:
        applies-to: "version-updates"
        patterns:
          - "*"
        update-types:
          - "patch"
          - "minor"

  - package-ecosystem: "npm"
    directory: "dashboard"
    schedule:
      interval: "cron"
      cronjob: "30 7 * * *"
      timezone: "Europe/London"
    target-branch: "main"
    groups:
      typescript:
        applies-to: "version-updates"
        patterns:
          - "*"
        update-types:
          - "patch"
          - "minor"
