name: "Setup Scanner Dependencies"
description: "Installs the dependencies for the scanner"

runs:
  using: "composite"
  steps:
    - name: Install Python and UV
      uses: astral-sh/setup-uv@85856786d1ce8acfbcc2f13a5f3fbd6b938f9f41 # v7.1.2
      with:
        working-directory: "scanner"
    - name: Set up Just
      uses: extractions/setup-just@e33e0265a09d6d736e2ee1e0eb685ef1de4669ff # v3.0.0
    - name: Install Python Dependencies
      shell: bash
      run: just scanner::install
