name: "Code Checks"

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: read

env:
  FORCE_COLOR: 1

jobs:
  common-code-checks:
    name: Common Code Checks
    permissions:
      contents: read
      actions: read # Allow the workflow to read actions metadata
      pull-requests: write # Allow the workflow to create and modify pull request comments
      security-events: write # Allow the workflow to upload analysis results
    uses: JackPlowman/reusable-workflows/.github/workflows/common-code-checks.yml@a5950751b77827654b888eb6b52a5c7fbca3e4fa # v2025.09.30.01
    secrets:
      workflow_github_token: ${{ secrets.GITHUB_TOKEN }}

  codeql-checks:
    name: CodeQL Analysis
    permissions:
      contents: read
      security-events: write # Allow the workflow to upload analysis results
    strategy:
      matrix:
        language: [actions, typescript, python]
    uses: JackPlowman/reusable-workflows/.github/workflows/codeql-analysis.yml@a5950751b77827654b888eb6b52a5c7fbca3e4fa # v2025.09.30.01
    with:
      language: ${{ matrix.language }}

  unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Setup Scanner Dependencies
        uses: ./.github/actions/setup-scanner-dependencies
      - name: Run Unit Tests
        run: just scanner::unit-test
      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@fd88b7d7ccbaefd23d8f36f73b59db7a3d246602 # v6.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  run-python-scanner-lint-checks:
    name: Run Python Scanner Lint Checks
    runs-on: ubuntu-latest
    permissions:
      security-events: write # Allow the workflow to upload analysis results
    steps:
      - name: Checkout Repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Set up dependencies
        uses: ./.github/actions/setup-scanner-dependencies
      - name: Generate Ruff Sarif
        run: just scanner::ruff-lint-check
        env:
          RUFF_OUTPUT_FORMAT: "sarif"
          RUFF_OUTPUT_FILE: "ruff-results.sarif"
        continue-on-error: true
      - name: Upload Ruff analysis results to GitHub
        uses: github/codeql-action/upload-sarif@16140ae1a102900babc80a33c44059580f687047 # v4.30.9
        with:
          sarif_file: scanner/ruff-results.sarif
          wait-for-processing: true
      - name: Check Python Code Linting (Ruff)
        run: just scanner::ruff-lint-check
        env:
          RUFF_OUTPUT_FORMAT: "github"

  run-python-scanner-format-checks:
    name: Run Python Scanner Format Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Set up dependencies
        uses: ./.github/actions/setup-scanner-dependencies
      - name: Check Python Code Format (Ruff)
        run: just scanner::ruff-format-check
        env:
          RUFF_OUTPUT_FORMAT: "github"

  run-python-scanner-type-checks:
    name: Run Python Scanner Type Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Set up dependencies
        uses: ./.github/actions/setup-scanner-dependencies
      - name: Check Python Code Types (ty) Checks
        run: just scanner::ty-check

  run-python-scanner-dead-code-checks:
    name: Run Python Scanner Dead Code Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Set up dependencies
        uses: ./.github/actions/setup-scanner-dependencies
      - name: Check Python Code for Dead Code (Vulture)
        run: just scanner::vulture

  run-python-scanner-lockfile-check:
    name: Run Python Scanner Lockfile Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Set up dependencies
        uses: ./.github/actions/setup-scanner-dependencies
      - name: Check UV Lockfile
        run: just scanner::uv-lock-check

  run-python-tests-lint-checks:
    name: Run Python Tests Lint Checks
    runs-on: ubuntu-latest
    permissions:
      security-events: write # Allow the workflow to upload analysis results
    steps:
      - name: Checkout Repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Set up dependencies
        uses: ./.github/actions/setup-tests-dependencies
      - name: Generate Ruff Sarif
        run: just tests::ruff-lint-check
        env:
          RUFF_OUTPUT_FORMAT: "sarif"
          RUFF_OUTPUT_FILE: "ruff-results.sarif"
        continue-on-error: true
      - name: Upload Ruff analysis results to GitHub
        uses: github/codeql-action/upload-sarif@16140ae1a102900babc80a33c44059580f687047 # v4.30.9
        with:
          sarif_file: tests/ruff-results.sarif
          wait-for-processing: true
      - name: Check Python Code Linting (Ruff)
        run: just tests::ruff-lint-check
        env:
          RUFF_OUTPUT_FORMAT: "github"

  run-python-tests-format-checks:
    name: Run Python Tests Format Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Set up dependencies
        uses: ./.github/actions/setup-tests-dependencies
      - name: Check Python Code Format (Ruff)
        run: just tests::ruff-format-check
        env:
          RUFF_OUTPUT_FORMAT: "github"

  run-python-tests-type-checks:
    name: Run Python Tests Type Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Set up dependencies
        uses: ./.github/actions/setup-tests-dependencies
      - name: Check Python Code Types (ty) Checks
        run: just tests::ty-check

  run-python-tests-lockfile-check:
    name: Run Python Tests Lockfile Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Set up dependencies
        uses: ./.github/actions/setup-tests-dependencies
      - name: Check UV Lockfile
        run: just tests::uv-lock-check

  run-typescript-dashboard-code-checks:
    name: Run TypeScript Dashboard Code Checks
    runs-on: ubuntu-latest
    permissions:
      security-events: write # Allow the workflow to upload analysis results
    steps:
      - name: Checkout Repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Setup Dashboard Dependencies
        uses: ./.github/actions/setup-dashboard-dependencies
      - name: Run ESLint
        env:
          SARIF_ESLINT_IGNORE_SUPPRESSED: "true"
        run: just dashboard::eslint-with-sarif
        continue-on-error: true
      - name: Upload analysis results to GitHub
        uses: github/codeql-action/upload-sarif@16140ae1a102900babc80a33c44059580f687047 # v4.30.9
        with:
          sarif_file: dashboard/eslint-results.sarif
          wait-for-processing: true
      - name: Run ESLint
        run: just dashboard::lint

  run-typescript-dashboard-format-checks:
    name: Run TypeScript Dashboard Format Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Setup Dashboard Dependencies
        uses: ./.github/actions/setup-dashboard-dependencies
      - name: Run Prettier
        run: just dashboard::prettier-check
