name: "Code Checks"

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: read
  packages: read

env:
  FORCE_COLOR: 1

jobs:
  check-code-quality:
    name: Check Code Quality
    runs-on: ubuntu-latest
    permissions:
      statuses: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Lint Code Base
        uses: super-linter/super-linter@5119dcd8011e92182ce8219d9e9efc82f16fddb6 # v8.0.0
        env:
          VALIDATE_ALL_CODEBASE: true
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LINTER_RULES_PATH: .github/super-linter-configurations
          YAML_ERROR_ON_WARNING: true
          VALIDATE_PYTHON_BLACK: false
          VALIDATE_PYTHON_FLAKE8: false
          VALIDATE_PYTHON_ISORT: false
          VALIDATE_PYTHON_MYPY: false
          VALIDATE_PYTHON_PYLINT: false
          VALIDATE_PYTHON_RUFF: false
          VALIDATE_PYTHON_PYINK: false
          VALIDATE_CSS: false
          VALIDATE_JSON: false
          VALIDATE_JAVASCRIPT_ES: false
          VALIDATE_JAVASCRIPT_PRETTIER: false
          VALIDATE_JAVASCRIPT_STANDARD: false
          VALIDATE_JSX: false
          VALIDATE_JSX_PRETTIER: false
          VALIDATE_TYPESCRIPT_ES: false
          VALIDATE_TYPESCRIPT_PRETTIER: false
          VALIDATE_TYPESCRIPT_STANDARD: false
          VALIDATE_TSX: false
          VALIDATE_TSX_PRETTIER: false

  common-code-checks:
    name: Common Code Checks
    permissions:
      contents: read
      actions: read
      pull-requests: write
      security-events: write
    uses: JackPlowman/reusable-workflows/.github/workflows/common-code-checks.yml@e5bce22fac6a92a28630f44ea3dfb21f817fabbb # v2025.07.22.03
    secrets:
      workflow_github_token: ${{ secrets.GITHUB_TOKEN }}

  codeql-checks:
    name: CodeQL Analysis
    permissions:
      contents: read
      security-events: write
    strategy:
      matrix:
        language: [actions, typescript, python]
    uses: JackPlowman/reusable-workflows/.github/workflows/codeql-analysis.yml@e5bce22fac6a92a28630f44ea3dfb21f817fabbb # v2025.07.22.03
    with:
      language: ${{ matrix.language }}

  unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Setup Scanner Dependencies
        uses: ./.github/actions/setup-scanner-dependencies
      - name: Run Unit Tests
        run: just scanner::unit-test
      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@8c71dc039c2dd71d3821e89a2b58ecc7fee6ced9 # v5.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  run-python-scanner-lint-checks:
    name: Run Python Scanner Lint Checks
    runs-on: ubuntu-latest
    permissions:
      statuses: write
      security-events: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Set up dependencies
        uses: ./.github/actions/setup-scanner-dependencies
      - name: Generate Ruff Sarif
        run: just scanner::ruff-lint-check
        env:
          RUFF_OUTPUT_FORMAT: "sarif"
          RUFF_OUTPUT_FILE: "ruff-results.sarif"
        continue-on-error: true
      - name: Upload Ruff analysis results to GitHub
        uses: github/codeql-action/upload-sarif@d6bbdef45e766d081b84a2def353b0055f728d3e # v3.29.3
        with:
          sarif_file: scanner/ruff-results.sarif
          wait-for-processing: true
      - name: Check Python Code Linting (Ruff)
        run: just scanner::ruff-lint-check
        env:
          RUFF_OUTPUT_FORMAT: "github"

  run-python-scanner-format-checks:
    name: Run Python Scanner Format Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Set up dependencies
        uses: ./.github/actions/setup-scanner-dependencies
      - name: Check Python Code Format (Ruff)
        run: just scanner::ruff-format-check
        env:
          RUFF_OUTPUT_FORMAT: "github"

  run-python-scanner-type-checks:
    name: Run Python Scanner Type Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Set up dependencies
        uses: ./.github/actions/setup-scanner-dependencies
      - name: Check Python Code Types (ty) Checks
        run: just scanner::ty-check

  run-python-scanner-dead-code-checks:
    name: Run Python Scanner Dead Code Checks
    runs-on: ubuntu-latest
    permissions:
      statuses: write
      security-events: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Set up dependencies
        uses: ./.github/actions/setup-scanner-dependencies
      - name: Check Python Code for Dead Code (Vulture)
        run: just scanner::vulture

  run-python-scanner-lockfile-check:
    name: Run Python Scanner Lockfile Check
    runs-on: ubuntu-latest
    permissions:
      statuses: write
      security-events: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Set up dependencies
        uses: ./.github/actions/setup-scanner-dependencies
      - name: Check UV Lockfile
        run: just scanner::uv-lock-check

  run-python-tests-lint-checks:
    name: Run Python Tests Lint Checks
    runs-on: ubuntu-latest
    permissions:
      statuses: write
      security-events: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Set up dependencies
        uses: ./.github/actions/setup-tests-dependencies
      - name: Generate Ruff Sarif
        run: just tests::ruff-lint-check
        env:
          RUFF_OUTPUT_FORMAT: "sarif"
          RUFF_OUTPUT_FILE: "ruff-results.sarif"
        continue-on-error: true
      - name: Upload Ruff analysis results to GitHub
        uses: github/codeql-action/upload-sarif@d6bbdef45e766d081b84a2def353b0055f728d3e # v3.29.3
        with:
          sarif_file: tests/ruff-results.sarif
          wait-for-processing: true
      - name: Check Python Code Linting (Ruff)
        run: just tests::ruff-lint-check
        env:
          RUFF_OUTPUT_FORMAT: "github"

  run-python-tests-format-checks:
    name: Run Python Tests Format Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Set up dependencies
        uses: ./.github/actions/setup-tests-dependencies
      - name: Check Python Code Format (Ruff)
        run: just tests::ruff-format-check
        env:
          RUFF_OUTPUT_FORMAT: "github"

  run-python-tests-type-checks:
    name: Run Python Tests Type Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Set up dependencies
        uses: ./.github/actions/setup-tests-dependencies
      - name: Check Python Code Types (ty) Checks
        run: just tests::ty-check

  run-python-tests-lockfile-check:
    name: Run Python Tests Lockfile Check
    runs-on: ubuntu-latest
    permissions:
      statuses: write
      security-events: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Set up dependencies
        uses: ./.github/actions/setup-tests-dependencies
      - name: Check UV Lockfile
        run: just tests::uv-lock-check
